/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ProtectedRouteImport } from './routes/_protected'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PublicTripInstancesRouteImport } from './routes/public.trip-instances'
import { Route as ProtectedSetupRouteImport } from './routes/_protected.setup'
import { Route as ProtectedOrganizationsRouteImport } from './routes/_protected.organizations'
import { Route as ProtectedMyBookingsRouteImport } from './routes/_protected.my-bookings'
import { Route as PublicTripInstancesIndexRouteImport } from './routes/public.trip-instances.index'
import { Route as PublicTripInstancesIdRouteImport } from './routes/public.trip-instances.$id'
import { Route as PublicOrganizationsSlugRouteImport } from './routes/public.organizations.$slug'
import { Route as ProtectedTripsOrgIdRouteImport } from './routes/_protected.trips.$orgId'
import { Route as ProtectedMyBookingsBookingIdRouteImport } from './routes/_protected.my-bookings.$bookingId'
import { Route as ProtectedTripsOrgIdTripIdRouteImport } from './routes/_protected.trips.$orgId.$tripId'
import { Route as ProtectedTripsOrgIdTripIdBookRouteImport } from './routes/_protected.trips.$orgId.$tripId.book'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ProtectedRoute = ProtectedRouteImport.update({
  id: '/_protected',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PublicTripInstancesRoute = PublicTripInstancesRouteImport.update({
  id: '/public/trip-instances',
  path: '/public/trip-instances',
  getParentRoute: () => rootRouteImport,
} as any)
const ProtectedSetupRoute = ProtectedSetupRouteImport.update({
  id: '/setup',
  path: '/setup',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedOrganizationsRoute = ProtectedOrganizationsRouteImport.update({
  id: '/organizations',
  path: '/organizations',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedMyBookingsRoute = ProtectedMyBookingsRouteImport.update({
  id: '/my-bookings',
  path: '/my-bookings',
  getParentRoute: () => ProtectedRoute,
} as any)
const PublicTripInstancesIndexRoute =
  PublicTripInstancesIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => PublicTripInstancesRoute,
  } as any)
const PublicTripInstancesIdRoute = PublicTripInstancesIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => PublicTripInstancesRoute,
} as any)
const PublicOrganizationsSlugRoute = PublicOrganizationsSlugRouteImport.update({
  id: '/public/organizations/$slug',
  path: '/public/organizations/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ProtectedTripsOrgIdRoute = ProtectedTripsOrgIdRouteImport.update({
  id: '/trips/$orgId',
  path: '/trips/$orgId',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedMyBookingsBookingIdRoute =
  ProtectedMyBookingsBookingIdRouteImport.update({
    id: '/$bookingId',
    path: '/$bookingId',
    getParentRoute: () => ProtectedMyBookingsRoute,
  } as any)
const ProtectedTripsOrgIdTripIdRoute =
  ProtectedTripsOrgIdTripIdRouteImport.update({
    id: '/$tripId',
    path: '/$tripId',
    getParentRoute: () => ProtectedTripsOrgIdRoute,
  } as any)
const ProtectedTripsOrgIdTripIdBookRoute =
  ProtectedTripsOrgIdTripIdBookRouteImport.update({
    id: '/book',
    path: '/book',
    getParentRoute: () => ProtectedTripsOrgIdTripIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/my-bookings': typeof ProtectedMyBookingsRouteWithChildren
  '/organizations': typeof ProtectedOrganizationsRoute
  '/setup': typeof ProtectedSetupRoute
  '/public/trip-instances': typeof PublicTripInstancesRouteWithChildren
  '/my-bookings/$bookingId': typeof ProtectedMyBookingsBookingIdRoute
  '/trips/$orgId': typeof ProtectedTripsOrgIdRouteWithChildren
  '/public/organizations/$slug': typeof PublicOrganizationsSlugRoute
  '/public/trip-instances/$id': typeof PublicTripInstancesIdRoute
  '/public/trip-instances/': typeof PublicTripInstancesIndexRoute
  '/trips/$orgId/$tripId': typeof ProtectedTripsOrgIdTripIdRouteWithChildren
  '/trips/$orgId/$tripId/book': typeof ProtectedTripsOrgIdTripIdBookRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/my-bookings': typeof ProtectedMyBookingsRouteWithChildren
  '/organizations': typeof ProtectedOrganizationsRoute
  '/setup': typeof ProtectedSetupRoute
  '/my-bookings/$bookingId': typeof ProtectedMyBookingsBookingIdRoute
  '/trips/$orgId': typeof ProtectedTripsOrgIdRouteWithChildren
  '/public/organizations/$slug': typeof PublicOrganizationsSlugRoute
  '/public/trip-instances/$id': typeof PublicTripInstancesIdRoute
  '/public/trip-instances': typeof PublicTripInstancesIndexRoute
  '/trips/$orgId/$tripId': typeof ProtectedTripsOrgIdTripIdRouteWithChildren
  '/trips/$orgId/$tripId/book': typeof ProtectedTripsOrgIdTripIdBookRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_protected': typeof ProtectedRouteWithChildren
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/_protected/my-bookings': typeof ProtectedMyBookingsRouteWithChildren
  '/_protected/organizations': typeof ProtectedOrganizationsRoute
  '/_protected/setup': typeof ProtectedSetupRoute
  '/public/trip-instances': typeof PublicTripInstancesRouteWithChildren
  '/_protected/my-bookings/$bookingId': typeof ProtectedMyBookingsBookingIdRoute
  '/_protected/trips/$orgId': typeof ProtectedTripsOrgIdRouteWithChildren
  '/public/organizations/$slug': typeof PublicOrganizationsSlugRoute
  '/public/trip-instances/$id': typeof PublicTripInstancesIdRoute
  '/public/trip-instances/': typeof PublicTripInstancesIndexRoute
  '/_protected/trips/$orgId/$tripId': typeof ProtectedTripsOrgIdTripIdRouteWithChildren
  '/_protected/trips/$orgId/$tripId/book': typeof ProtectedTripsOrgIdTripIdBookRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/signup'
    | '/my-bookings'
    | '/organizations'
    | '/setup'
    | '/public/trip-instances'
    | '/my-bookings/$bookingId'
    | '/trips/$orgId'
    | '/public/organizations/$slug'
    | '/public/trip-instances/$id'
    | '/public/trip-instances/'
    | '/trips/$orgId/$tripId'
    | '/trips/$orgId/$tripId/book'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/signup'
    | '/my-bookings'
    | '/organizations'
    | '/setup'
    | '/my-bookings/$bookingId'
    | '/trips/$orgId'
    | '/public/organizations/$slug'
    | '/public/trip-instances/$id'
    | '/public/trip-instances'
    | '/trips/$orgId/$tripId'
    | '/trips/$orgId/$tripId/book'
  id:
    | '__root__'
    | '/'
    | '/_protected'
    | '/login'
    | '/signup'
    | '/_protected/my-bookings'
    | '/_protected/organizations'
    | '/_protected/setup'
    | '/public/trip-instances'
    | '/_protected/my-bookings/$bookingId'
    | '/_protected/trips/$orgId'
    | '/public/organizations/$slug'
    | '/public/trip-instances/$id'
    | '/public/trip-instances/'
    | '/_protected/trips/$orgId/$tripId'
    | '/_protected/trips/$orgId/$tripId/book'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ProtectedRoute: typeof ProtectedRouteWithChildren
  LoginRoute: typeof LoginRoute
  SignupRoute: typeof SignupRoute
  PublicTripInstancesRoute: typeof PublicTripInstancesRouteWithChildren
  PublicOrganizationsSlugRoute: typeof PublicOrganizationsSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_protected': {
      id: '/_protected'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof ProtectedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/public/trip-instances': {
      id: '/public/trip-instances'
      path: '/public/trip-instances'
      fullPath: '/public/trip-instances'
      preLoaderRoute: typeof PublicTripInstancesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_protected/setup': {
      id: '/_protected/setup'
      path: '/setup'
      fullPath: '/setup'
      preLoaderRoute: typeof ProtectedSetupRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/organizations': {
      id: '/_protected/organizations'
      path: '/organizations'
      fullPath: '/organizations'
      preLoaderRoute: typeof ProtectedOrganizationsRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/my-bookings': {
      id: '/_protected/my-bookings'
      path: '/my-bookings'
      fullPath: '/my-bookings'
      preLoaderRoute: typeof ProtectedMyBookingsRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/public/trip-instances/': {
      id: '/public/trip-instances/'
      path: '/'
      fullPath: '/public/trip-instances/'
      preLoaderRoute: typeof PublicTripInstancesIndexRouteImport
      parentRoute: typeof PublicTripInstancesRoute
    }
    '/public/trip-instances/$id': {
      id: '/public/trip-instances/$id'
      path: '/$id'
      fullPath: '/public/trip-instances/$id'
      preLoaderRoute: typeof PublicTripInstancesIdRouteImport
      parentRoute: typeof PublicTripInstancesRoute
    }
    '/public/organizations/$slug': {
      id: '/public/organizations/$slug'
      path: '/public/organizations/$slug'
      fullPath: '/public/organizations/$slug'
      preLoaderRoute: typeof PublicOrganizationsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_protected/trips/$orgId': {
      id: '/_protected/trips/$orgId'
      path: '/trips/$orgId'
      fullPath: '/trips/$orgId'
      preLoaderRoute: typeof ProtectedTripsOrgIdRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/my-bookings/$bookingId': {
      id: '/_protected/my-bookings/$bookingId'
      path: '/$bookingId'
      fullPath: '/my-bookings/$bookingId'
      preLoaderRoute: typeof ProtectedMyBookingsBookingIdRouteImport
      parentRoute: typeof ProtectedMyBookingsRoute
    }
    '/_protected/trips/$orgId/$tripId': {
      id: '/_protected/trips/$orgId/$tripId'
      path: '/$tripId'
      fullPath: '/trips/$orgId/$tripId'
      preLoaderRoute: typeof ProtectedTripsOrgIdTripIdRouteImport
      parentRoute: typeof ProtectedTripsOrgIdRoute
    }
    '/_protected/trips/$orgId/$tripId/book': {
      id: '/_protected/trips/$orgId/$tripId/book'
      path: '/book'
      fullPath: '/trips/$orgId/$tripId/book'
      preLoaderRoute: typeof ProtectedTripsOrgIdTripIdBookRouteImport
      parentRoute: typeof ProtectedTripsOrgIdTripIdRoute
    }
  }
}

interface ProtectedMyBookingsRouteChildren {
  ProtectedMyBookingsBookingIdRoute: typeof ProtectedMyBookingsBookingIdRoute
}

const ProtectedMyBookingsRouteChildren: ProtectedMyBookingsRouteChildren = {
  ProtectedMyBookingsBookingIdRoute: ProtectedMyBookingsBookingIdRoute,
}

const ProtectedMyBookingsRouteWithChildren =
  ProtectedMyBookingsRoute._addFileChildren(ProtectedMyBookingsRouteChildren)

interface ProtectedTripsOrgIdTripIdRouteChildren {
  ProtectedTripsOrgIdTripIdBookRoute: typeof ProtectedTripsOrgIdTripIdBookRoute
}

const ProtectedTripsOrgIdTripIdRouteChildren: ProtectedTripsOrgIdTripIdRouteChildren =
  {
    ProtectedTripsOrgIdTripIdBookRoute: ProtectedTripsOrgIdTripIdBookRoute,
  }

const ProtectedTripsOrgIdTripIdRouteWithChildren =
  ProtectedTripsOrgIdTripIdRoute._addFileChildren(
    ProtectedTripsOrgIdTripIdRouteChildren,
  )

interface ProtectedTripsOrgIdRouteChildren {
  ProtectedTripsOrgIdTripIdRoute: typeof ProtectedTripsOrgIdTripIdRouteWithChildren
}

const ProtectedTripsOrgIdRouteChildren: ProtectedTripsOrgIdRouteChildren = {
  ProtectedTripsOrgIdTripIdRoute: ProtectedTripsOrgIdTripIdRouteWithChildren,
}

const ProtectedTripsOrgIdRouteWithChildren =
  ProtectedTripsOrgIdRoute._addFileChildren(ProtectedTripsOrgIdRouteChildren)

interface ProtectedRouteChildren {
  ProtectedMyBookingsRoute: typeof ProtectedMyBookingsRouteWithChildren
  ProtectedOrganizationsRoute: typeof ProtectedOrganizationsRoute
  ProtectedSetupRoute: typeof ProtectedSetupRoute
  ProtectedTripsOrgIdRoute: typeof ProtectedTripsOrgIdRouteWithChildren
}

const ProtectedRouteChildren: ProtectedRouteChildren = {
  ProtectedMyBookingsRoute: ProtectedMyBookingsRouteWithChildren,
  ProtectedOrganizationsRoute: ProtectedOrganizationsRoute,
  ProtectedSetupRoute: ProtectedSetupRoute,
  ProtectedTripsOrgIdRoute: ProtectedTripsOrgIdRouteWithChildren,
}

const ProtectedRouteWithChildren = ProtectedRoute._addFileChildren(
  ProtectedRouteChildren,
)

interface PublicTripInstancesRouteChildren {
  PublicTripInstancesIdRoute: typeof PublicTripInstancesIdRoute
  PublicTripInstancesIndexRoute: typeof PublicTripInstancesIndexRoute
}

const PublicTripInstancesRouteChildren: PublicTripInstancesRouteChildren = {
  PublicTripInstancesIdRoute: PublicTripInstancesIdRoute,
  PublicTripInstancesIndexRoute: PublicTripInstancesIndexRoute,
}

const PublicTripInstancesRouteWithChildren =
  PublicTripInstancesRoute._addFileChildren(PublicTripInstancesRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ProtectedRoute: ProtectedRouteWithChildren,
  LoginRoute: LoginRoute,
  SignupRoute: SignupRoute,
  PublicTripInstancesRoute: PublicTripInstancesRouteWithChildren,
  PublicOrganizationsSlugRoute: PublicOrganizationsSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
