/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ProtectedRouteImport } from './routes/_protected'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PublicTripInstancesRouteImport } from './routes/public.trip-instances'
import { Route as ProtectedSetupRouteImport } from './routes/_protected.setup'
import { Route as ProtectedProfileRouteImport } from './routes/_protected.profile'
import { Route as ProtectedOrganizationsRouteImport } from './routes/_protected.organizations'
import { Route as ProtectedMyBookingsRouteImport } from './routes/_protected.my-bookings'
import { Route as ProtectedDriverRouteImport } from './routes/_protected._driver'
import { Route as ProtectedAdminRouteImport } from './routes/_protected._admin'
import { Route as PublicTripInstancesIndexRouteImport } from './routes/public.trip-instances.index'
import { Route as PublicTripInstancesIdRouteImport } from './routes/public.trip-instances.$id'
import { Route as PublicOrganizationsSlugRouteImport } from './routes/public.organizations.$slug'
import { Route as ProtectedTripsOrgIdRouteImport } from './routes/_protected.trips.$orgId'
import { Route as ProtectedMyBookingsBookingIdRouteImport } from './routes/_protected.my-bookings.$bookingId'
import { Route as ProtectedDriverMyTripsRouteImport } from './routes/_protected._driver.my-trips'
import { Route as ProtectedAdminTripsRouteImport } from './routes/_protected._admin.trips'
import { Route as ProtectedAdminTemplatesRouteImport } from './routes/_protected._admin.templates'
import { Route as ProtectedAdminOrganizationRouteImport } from './routes/_protected._admin.organization'
import { Route as ProtectedAdminDriversRouteImport } from './routes/_protected._admin.drivers'
import { Route as ProtectedAdminDashboardRouteImport } from './routes/_protected._admin.dashboard'
import { Route as ProtectedTripsOrgIdTripIdRouteImport } from './routes/_protected.trips.$orgId.$tripId'
import { Route as ProtectedTripsOrgIdTripIdBookRouteImport } from './routes/_protected.trips.$orgId.$tripId.book'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ProtectedRoute = ProtectedRouteImport.update({
  id: '/_protected',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PublicTripInstancesRoute = PublicTripInstancesRouteImport.update({
  id: '/public/trip-instances',
  path: '/public/trip-instances',
  getParentRoute: () => rootRouteImport,
} as any)
const ProtectedSetupRoute = ProtectedSetupRouteImport.update({
  id: '/setup',
  path: '/setup',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedProfileRoute = ProtectedProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedOrganizationsRoute = ProtectedOrganizationsRouteImport.update({
  id: '/organizations',
  path: '/organizations',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedMyBookingsRoute = ProtectedMyBookingsRouteImport.update({
  id: '/my-bookings',
  path: '/my-bookings',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedDriverRoute = ProtectedDriverRouteImport.update({
  id: '/_driver',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedAdminRoute = ProtectedAdminRouteImport.update({
  id: '/_admin',
  getParentRoute: () => ProtectedRoute,
} as any)
const PublicTripInstancesIndexRoute =
  PublicTripInstancesIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => PublicTripInstancesRoute,
  } as any)
const PublicTripInstancesIdRoute = PublicTripInstancesIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => PublicTripInstancesRoute,
} as any)
const PublicOrganizationsSlugRoute = PublicOrganizationsSlugRouteImport.update({
  id: '/public/organizations/$slug',
  path: '/public/organizations/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ProtectedTripsOrgIdRoute = ProtectedTripsOrgIdRouteImport.update({
  id: '/trips/$orgId',
  path: '/trips/$orgId',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedMyBookingsBookingIdRoute =
  ProtectedMyBookingsBookingIdRouteImport.update({
    id: '/$bookingId',
    path: '/$bookingId',
    getParentRoute: () => ProtectedMyBookingsRoute,
  } as any)
const ProtectedDriverMyTripsRoute = ProtectedDriverMyTripsRouteImport.update({
  id: '/my-trips',
  path: '/my-trips',
  getParentRoute: () => ProtectedDriverRoute,
} as any)
const ProtectedAdminTripsRoute = ProtectedAdminTripsRouteImport.update({
  id: '/trips',
  path: '/trips',
  getParentRoute: () => ProtectedAdminRoute,
} as any)
const ProtectedAdminTemplatesRoute = ProtectedAdminTemplatesRouteImport.update({
  id: '/templates',
  path: '/templates',
  getParentRoute: () => ProtectedAdminRoute,
} as any)
const ProtectedAdminOrganizationRoute =
  ProtectedAdminOrganizationRouteImport.update({
    id: '/organization',
    path: '/organization',
    getParentRoute: () => ProtectedAdminRoute,
  } as any)
const ProtectedAdminDriversRoute = ProtectedAdminDriversRouteImport.update({
  id: '/drivers',
  path: '/drivers',
  getParentRoute: () => ProtectedAdminRoute,
} as any)
const ProtectedAdminDashboardRoute = ProtectedAdminDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => ProtectedAdminRoute,
} as any)
const ProtectedTripsOrgIdTripIdRoute =
  ProtectedTripsOrgIdTripIdRouteImport.update({
    id: '/$tripId',
    path: '/$tripId',
    getParentRoute: () => ProtectedTripsOrgIdRoute,
  } as any)
const ProtectedTripsOrgIdTripIdBookRoute =
  ProtectedTripsOrgIdTripIdBookRouteImport.update({
    id: '/book',
    path: '/book',
    getParentRoute: () => ProtectedTripsOrgIdTripIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/my-bookings': typeof ProtectedMyBookingsRouteWithChildren
  '/organizations': typeof ProtectedOrganizationsRoute
  '/profile': typeof ProtectedProfileRoute
  '/setup': typeof ProtectedSetupRoute
  '/public/trip-instances': typeof PublicTripInstancesRouteWithChildren
  '/dashboard': typeof ProtectedAdminDashboardRoute
  '/drivers': typeof ProtectedAdminDriversRoute
  '/organization': typeof ProtectedAdminOrganizationRoute
  '/templates': typeof ProtectedAdminTemplatesRoute
  '/trips': typeof ProtectedAdminTripsRoute
  '/my-trips': typeof ProtectedDriverMyTripsRoute
  '/my-bookings/$bookingId': typeof ProtectedMyBookingsBookingIdRoute
  '/trips/$orgId': typeof ProtectedTripsOrgIdRouteWithChildren
  '/public/organizations/$slug': typeof PublicOrganizationsSlugRoute
  '/public/trip-instances/$id': typeof PublicTripInstancesIdRoute
  '/public/trip-instances/': typeof PublicTripInstancesIndexRoute
  '/trips/$orgId/$tripId': typeof ProtectedTripsOrgIdTripIdRouteWithChildren
  '/trips/$orgId/$tripId/book': typeof ProtectedTripsOrgIdTripIdBookRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/my-bookings': typeof ProtectedMyBookingsRouteWithChildren
  '/organizations': typeof ProtectedOrganizationsRoute
  '/profile': typeof ProtectedProfileRoute
  '/setup': typeof ProtectedSetupRoute
  '/dashboard': typeof ProtectedAdminDashboardRoute
  '/drivers': typeof ProtectedAdminDriversRoute
  '/organization': typeof ProtectedAdminOrganizationRoute
  '/templates': typeof ProtectedAdminTemplatesRoute
  '/trips': typeof ProtectedAdminTripsRoute
  '/my-trips': typeof ProtectedDriverMyTripsRoute
  '/my-bookings/$bookingId': typeof ProtectedMyBookingsBookingIdRoute
  '/trips/$orgId': typeof ProtectedTripsOrgIdRouteWithChildren
  '/public/organizations/$slug': typeof PublicOrganizationsSlugRoute
  '/public/trip-instances/$id': typeof PublicTripInstancesIdRoute
  '/public/trip-instances': typeof PublicTripInstancesIndexRoute
  '/trips/$orgId/$tripId': typeof ProtectedTripsOrgIdTripIdRouteWithChildren
  '/trips/$orgId/$tripId/book': typeof ProtectedTripsOrgIdTripIdBookRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_protected': typeof ProtectedRouteWithChildren
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/_protected/_admin': typeof ProtectedAdminRouteWithChildren
  '/_protected/_driver': typeof ProtectedDriverRouteWithChildren
  '/_protected/my-bookings': typeof ProtectedMyBookingsRouteWithChildren
  '/_protected/organizations': typeof ProtectedOrganizationsRoute
  '/_protected/profile': typeof ProtectedProfileRoute
  '/_protected/setup': typeof ProtectedSetupRoute
  '/public/trip-instances': typeof PublicTripInstancesRouteWithChildren
  '/_protected/_admin/dashboard': typeof ProtectedAdminDashboardRoute
  '/_protected/_admin/drivers': typeof ProtectedAdminDriversRoute
  '/_protected/_admin/organization': typeof ProtectedAdminOrganizationRoute
  '/_protected/_admin/templates': typeof ProtectedAdminTemplatesRoute
  '/_protected/_admin/trips': typeof ProtectedAdminTripsRoute
  '/_protected/_driver/my-trips': typeof ProtectedDriverMyTripsRoute
  '/_protected/my-bookings/$bookingId': typeof ProtectedMyBookingsBookingIdRoute
  '/_protected/trips/$orgId': typeof ProtectedTripsOrgIdRouteWithChildren
  '/public/organizations/$slug': typeof PublicOrganizationsSlugRoute
  '/public/trip-instances/$id': typeof PublicTripInstancesIdRoute
  '/public/trip-instances/': typeof PublicTripInstancesIndexRoute
  '/_protected/trips/$orgId/$tripId': typeof ProtectedTripsOrgIdTripIdRouteWithChildren
  '/_protected/trips/$orgId/$tripId/book': typeof ProtectedTripsOrgIdTripIdBookRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/signup'
    | '/my-bookings'
    | '/organizations'
    | '/profile'
    | '/setup'
    | '/public/trip-instances'
    | '/dashboard'
    | '/drivers'
    | '/organization'
    | '/templates'
    | '/trips'
    | '/my-trips'
    | '/my-bookings/$bookingId'
    | '/trips/$orgId'
    | '/public/organizations/$slug'
    | '/public/trip-instances/$id'
    | '/public/trip-instances/'
    | '/trips/$orgId/$tripId'
    | '/trips/$orgId/$tripId/book'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/signup'
    | '/my-bookings'
    | '/organizations'
    | '/profile'
    | '/setup'
    | '/dashboard'
    | '/drivers'
    | '/organization'
    | '/templates'
    | '/trips'
    | '/my-trips'
    | '/my-bookings/$bookingId'
    | '/trips/$orgId'
    | '/public/organizations/$slug'
    | '/public/trip-instances/$id'
    | '/public/trip-instances'
    | '/trips/$orgId/$tripId'
    | '/trips/$orgId/$tripId/book'
  id:
    | '__root__'
    | '/'
    | '/_protected'
    | '/login'
    | '/signup'
    | '/_protected/_admin'
    | '/_protected/_driver'
    | '/_protected/my-bookings'
    | '/_protected/organizations'
    | '/_protected/profile'
    | '/_protected/setup'
    | '/public/trip-instances'
    | '/_protected/_admin/dashboard'
    | '/_protected/_admin/drivers'
    | '/_protected/_admin/organization'
    | '/_protected/_admin/templates'
    | '/_protected/_admin/trips'
    | '/_protected/_driver/my-trips'
    | '/_protected/my-bookings/$bookingId'
    | '/_protected/trips/$orgId'
    | '/public/organizations/$slug'
    | '/public/trip-instances/$id'
    | '/public/trip-instances/'
    | '/_protected/trips/$orgId/$tripId'
    | '/_protected/trips/$orgId/$tripId/book'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ProtectedRoute: typeof ProtectedRouteWithChildren
  LoginRoute: typeof LoginRoute
  SignupRoute: typeof SignupRoute
  PublicTripInstancesRoute: typeof PublicTripInstancesRouteWithChildren
  PublicOrganizationsSlugRoute: typeof PublicOrganizationsSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_protected': {
      id: '/_protected'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof ProtectedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/public/trip-instances': {
      id: '/public/trip-instances'
      path: '/public/trip-instances'
      fullPath: '/public/trip-instances'
      preLoaderRoute: typeof PublicTripInstancesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_protected/setup': {
      id: '/_protected/setup'
      path: '/setup'
      fullPath: '/setup'
      preLoaderRoute: typeof ProtectedSetupRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/profile': {
      id: '/_protected/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProtectedProfileRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/organizations': {
      id: '/_protected/organizations'
      path: '/organizations'
      fullPath: '/organizations'
      preLoaderRoute: typeof ProtectedOrganizationsRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/my-bookings': {
      id: '/_protected/my-bookings'
      path: '/my-bookings'
      fullPath: '/my-bookings'
      preLoaderRoute: typeof ProtectedMyBookingsRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/_driver': {
      id: '/_protected/_driver'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof ProtectedDriverRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/_admin': {
      id: '/_protected/_admin'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof ProtectedAdminRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/public/trip-instances/': {
      id: '/public/trip-instances/'
      path: '/'
      fullPath: '/public/trip-instances/'
      preLoaderRoute: typeof PublicTripInstancesIndexRouteImport
      parentRoute: typeof PublicTripInstancesRoute
    }
    '/public/trip-instances/$id': {
      id: '/public/trip-instances/$id'
      path: '/$id'
      fullPath: '/public/trip-instances/$id'
      preLoaderRoute: typeof PublicTripInstancesIdRouteImport
      parentRoute: typeof PublicTripInstancesRoute
    }
    '/public/organizations/$slug': {
      id: '/public/organizations/$slug'
      path: '/public/organizations/$slug'
      fullPath: '/public/organizations/$slug'
      preLoaderRoute: typeof PublicOrganizationsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_protected/trips/$orgId': {
      id: '/_protected/trips/$orgId'
      path: '/trips/$orgId'
      fullPath: '/trips/$orgId'
      preLoaderRoute: typeof ProtectedTripsOrgIdRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/my-bookings/$bookingId': {
      id: '/_protected/my-bookings/$bookingId'
      path: '/$bookingId'
      fullPath: '/my-bookings/$bookingId'
      preLoaderRoute: typeof ProtectedMyBookingsBookingIdRouteImport
      parentRoute: typeof ProtectedMyBookingsRoute
    }
    '/_protected/_driver/my-trips': {
      id: '/_protected/_driver/my-trips'
      path: '/my-trips'
      fullPath: '/my-trips'
      preLoaderRoute: typeof ProtectedDriverMyTripsRouteImport
      parentRoute: typeof ProtectedDriverRoute
    }
    '/_protected/_admin/trips': {
      id: '/_protected/_admin/trips'
      path: '/trips'
      fullPath: '/trips'
      preLoaderRoute: typeof ProtectedAdminTripsRouteImport
      parentRoute: typeof ProtectedAdminRoute
    }
    '/_protected/_admin/templates': {
      id: '/_protected/_admin/templates'
      path: '/templates'
      fullPath: '/templates'
      preLoaderRoute: typeof ProtectedAdminTemplatesRouteImport
      parentRoute: typeof ProtectedAdminRoute
    }
    '/_protected/_admin/organization': {
      id: '/_protected/_admin/organization'
      path: '/organization'
      fullPath: '/organization'
      preLoaderRoute: typeof ProtectedAdminOrganizationRouteImport
      parentRoute: typeof ProtectedAdminRoute
    }
    '/_protected/_admin/drivers': {
      id: '/_protected/_admin/drivers'
      path: '/drivers'
      fullPath: '/drivers'
      preLoaderRoute: typeof ProtectedAdminDriversRouteImport
      parentRoute: typeof ProtectedAdminRoute
    }
    '/_protected/_admin/dashboard': {
      id: '/_protected/_admin/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof ProtectedAdminDashboardRouteImport
      parentRoute: typeof ProtectedAdminRoute
    }
    '/_protected/trips/$orgId/$tripId': {
      id: '/_protected/trips/$orgId/$tripId'
      path: '/$tripId'
      fullPath: '/trips/$orgId/$tripId'
      preLoaderRoute: typeof ProtectedTripsOrgIdTripIdRouteImport
      parentRoute: typeof ProtectedTripsOrgIdRoute
    }
    '/_protected/trips/$orgId/$tripId/book': {
      id: '/_protected/trips/$orgId/$tripId/book'
      path: '/book'
      fullPath: '/trips/$orgId/$tripId/book'
      preLoaderRoute: typeof ProtectedTripsOrgIdTripIdBookRouteImport
      parentRoute: typeof ProtectedTripsOrgIdTripIdRoute
    }
  }
}

interface ProtectedAdminRouteChildren {
  ProtectedAdminDashboardRoute: typeof ProtectedAdminDashboardRoute
  ProtectedAdminDriversRoute: typeof ProtectedAdminDriversRoute
  ProtectedAdminOrganizationRoute: typeof ProtectedAdminOrganizationRoute
  ProtectedAdminTemplatesRoute: typeof ProtectedAdminTemplatesRoute
  ProtectedAdminTripsRoute: typeof ProtectedAdminTripsRoute
}

const ProtectedAdminRouteChildren: ProtectedAdminRouteChildren = {
  ProtectedAdminDashboardRoute: ProtectedAdminDashboardRoute,
  ProtectedAdminDriversRoute: ProtectedAdminDriversRoute,
  ProtectedAdminOrganizationRoute: ProtectedAdminOrganizationRoute,
  ProtectedAdminTemplatesRoute: ProtectedAdminTemplatesRoute,
  ProtectedAdminTripsRoute: ProtectedAdminTripsRoute,
}

const ProtectedAdminRouteWithChildren = ProtectedAdminRoute._addFileChildren(
  ProtectedAdminRouteChildren,
)

interface ProtectedDriverRouteChildren {
  ProtectedDriverMyTripsRoute: typeof ProtectedDriverMyTripsRoute
}

const ProtectedDriverRouteChildren: ProtectedDriverRouteChildren = {
  ProtectedDriverMyTripsRoute: ProtectedDriverMyTripsRoute,
}

const ProtectedDriverRouteWithChildren = ProtectedDriverRoute._addFileChildren(
  ProtectedDriverRouteChildren,
)

interface ProtectedMyBookingsRouteChildren {
  ProtectedMyBookingsBookingIdRoute: typeof ProtectedMyBookingsBookingIdRoute
}

const ProtectedMyBookingsRouteChildren: ProtectedMyBookingsRouteChildren = {
  ProtectedMyBookingsBookingIdRoute: ProtectedMyBookingsBookingIdRoute,
}

const ProtectedMyBookingsRouteWithChildren =
  ProtectedMyBookingsRoute._addFileChildren(ProtectedMyBookingsRouteChildren)

interface ProtectedTripsOrgIdTripIdRouteChildren {
  ProtectedTripsOrgIdTripIdBookRoute: typeof ProtectedTripsOrgIdTripIdBookRoute
}

const ProtectedTripsOrgIdTripIdRouteChildren: ProtectedTripsOrgIdTripIdRouteChildren =
  {
    ProtectedTripsOrgIdTripIdBookRoute: ProtectedTripsOrgIdTripIdBookRoute,
  }

const ProtectedTripsOrgIdTripIdRouteWithChildren =
  ProtectedTripsOrgIdTripIdRoute._addFileChildren(
    ProtectedTripsOrgIdTripIdRouteChildren,
  )

interface ProtectedTripsOrgIdRouteChildren {
  ProtectedTripsOrgIdTripIdRoute: typeof ProtectedTripsOrgIdTripIdRouteWithChildren
}

const ProtectedTripsOrgIdRouteChildren: ProtectedTripsOrgIdRouteChildren = {
  ProtectedTripsOrgIdTripIdRoute: ProtectedTripsOrgIdTripIdRouteWithChildren,
}

const ProtectedTripsOrgIdRouteWithChildren =
  ProtectedTripsOrgIdRoute._addFileChildren(ProtectedTripsOrgIdRouteChildren)

interface ProtectedRouteChildren {
  ProtectedAdminRoute: typeof ProtectedAdminRouteWithChildren
  ProtectedDriverRoute: typeof ProtectedDriverRouteWithChildren
  ProtectedMyBookingsRoute: typeof ProtectedMyBookingsRouteWithChildren
  ProtectedOrganizationsRoute: typeof ProtectedOrganizationsRoute
  ProtectedProfileRoute: typeof ProtectedProfileRoute
  ProtectedSetupRoute: typeof ProtectedSetupRoute
  ProtectedTripsOrgIdRoute: typeof ProtectedTripsOrgIdRouteWithChildren
}

const ProtectedRouteChildren: ProtectedRouteChildren = {
  ProtectedAdminRoute: ProtectedAdminRouteWithChildren,
  ProtectedDriverRoute: ProtectedDriverRouteWithChildren,
  ProtectedMyBookingsRoute: ProtectedMyBookingsRouteWithChildren,
  ProtectedOrganizationsRoute: ProtectedOrganizationsRoute,
  ProtectedProfileRoute: ProtectedProfileRoute,
  ProtectedSetupRoute: ProtectedSetupRoute,
  ProtectedTripsOrgIdRoute: ProtectedTripsOrgIdRouteWithChildren,
}

const ProtectedRouteWithChildren = ProtectedRoute._addFileChildren(
  ProtectedRouteChildren,
)

interface PublicTripInstancesRouteChildren {
  PublicTripInstancesIdRoute: typeof PublicTripInstancesIdRoute
  PublicTripInstancesIndexRoute: typeof PublicTripInstancesIndexRoute
}

const PublicTripInstancesRouteChildren: PublicTripInstancesRouteChildren = {
  PublicTripInstancesIdRoute: PublicTripInstancesIdRoute,
  PublicTripInstancesIndexRoute: PublicTripInstancesIndexRoute,
}

const PublicTripInstancesRouteWithChildren =
  PublicTripInstancesRoute._addFileChildren(PublicTripInstancesRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ProtectedRoute: ProtectedRouteWithChildren,
  LoginRoute: LoginRoute,
  SignupRoute: SignupRoute,
  PublicTripInstancesRoute: PublicTripInstancesRouteWithChildren,
  PublicOrganizationsSlugRoute: PublicOrganizationsSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
